# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

target 'rainyShinyCloudy' do
pod 'Alamofire',
    :git => 'https://github.com/Alamofire/Alamofire.git',
    :branch => 'master'


  # Pods for rainyShinyCloudy

  target 'rainyShinyCloudyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'rainyShinyCloudyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
